//
//  ProfileInteractor.swift
//  PictureApp
//
//  Created by Ilham on 14/04/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func fetchUserData()
}

class ProfileInteractor: ProfileBusinessLogic {
    enum constant {
        static let usernameUserDefaultKey = "email"
    }
    
    var presenter: ProfilePresentationLogic?
    let userdefaults = UserDefaults.standard
    
    func fetchUserData() {
        if let email = userdefaults.string(forKey: constant.usernameUserDefaultKey) {
            presenter?.presentProfile(email: email)
        } else {
            presenter?.presentError()
        }
    }
}
