//
//  ProfilePresenter.swift
//  PictureApp
//
//  Created by Ilham on 14/04/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentProfile(email: String)
    func presentError()
}

class ProfilePresenter: ProfilePresentationLogic {
    enum Constant {
        static let errorMessage = "Something wrong when fetch data, please check form again"
    }
    
    weak var viewController: ProfileDisplayLogic?
    
    func presentProfile(email: String) {
        viewController?.displayProfile(email)
    }
    
    func presentError() {
        viewController?.displayError(Constant.errorMessage)
    }
    
}
