//
//  LoginInteractor.swift
//  PictureApp
//
//  Created by Ilham on 14/04/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func checkLoginData()
    func saveLoggedinData(email: String, password: String)
}

class LoginInteractor: LoginBusinessLogic {
    enum constant {
        static let usernameUserDefaultKey = "email"
        static let passwordUserDefaultKey = "password"
    }
    
    var presenter: LoginPresentationLogic?
    let userdefaults = UserDefaults.standard
    
    func checkLoginData() {
        guard let _ = userdefaults.string(forKey: constant.usernameUserDefaultKey), let _ = userdefaults.string(forKey: constant.passwordUserDefaultKey) else { return }
        presenter?.presentHomePage()
        
    }
    
    func saveLoggedinData(email: String, password: String) {
        if email.count > 0 && password.count > 0 {
            userdefaults.set(email, forKey: constant.usernameUserDefaultKey)
            userdefaults.set(password, forKey: constant.passwordUserDefaultKey)
            presenter?.presentHomePage()
        } else {
            presenter?.presentErrorSaveData()
        }
    }
}
