//
//  LoginRouter.swift
//  PictureApp
//
//  Created by Ilham on 14/04/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    func routeToHomePage()
}

class LoginRouter: LoginRoutingLogic {
    weak var viewController: LoginViewController?
    
    func routeToHomePage() {
        let storyBoard : UIStoryboard = UIStoryboard(name: "HomePage", bundle:nil)
        let nextViewController = storyBoard.instantiateViewController(withIdentifier: "HomePage") as! HomePage
        viewController?.navigationController?.pushViewController(nextViewController, animated: true)
    }
}
