//
//  LoginPresenter.swift
//  PictureApp
//
//  Created by Ilham on 14/04/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentHomePage()
    func presentErrorSaveData()
}

class LoginPresenter: LoginPresentationLogic {
    enum Constant {
        static let errorMessage = "Something wrong when save data, please check form again"
    }
    
    weak var viewController: LoginDisplayLogic?
    
    func presentHomePage() {
        viewController?.displaySuccessLogin()
    }
    
    func presentErrorSaveData() {
        viewController?.displayErrorSaveData(Constant.errorMessage)
    }
}
