//
//  HomeRouter.swift
//  PictureApp
//
//  Created by Ilham on 14/04/20.
//  Copyright (c) 2020 ilham. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic {
    func routeToDetailPict()
}

class HomeRouter: HomeRoutingLogic {
    weak var viewController: HomeViewController?
    
    // MARK: Routing
    
    func routeToDetailPict() {
        let detailVC = DetailViewController.instantiate()
        viewController?.navigationController?.pushViewController(detailVC, animated: true)
    }
}
